# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='desciption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='desciption_html',
            new_name='description_html',
        ),
    ]
